version: '3.8'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - rabbitmq-net
  node-app:
    build:
      context: . # Path to the directory containing your Dockerfile
      dockerfile: Dockerfile # Dockerfile name
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - ./src:/app/src
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge
